name: 'Clean up cloud rogue instances'
description: 'Javascript github action to clean up rogue instances in the cloud'
author: 'cellinacywinska & LorenzoDrudi'
branding:
  icon: 'archive'
  color: 'purple'
inputs:
  repo-name:
    description: 'The name of the repo where the runners are linked to'
    required: true
    default: ''
  aws-region:
    description: 'AWS region where the instances are located'
    required: true
    default: 'eu-west-2'
runs:
  using: 'node16'
  main: 'dist/index.js'
